version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: bedyeru17
      MYSQL_DATABASE: board_db
      MYSQL_USER: lhe
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - my-network

  springboot:
    build: .
    container_name: my-springboot
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/board_db
      SPRING_DATASOURCE_USERNAME: lhe
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
